/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseMapSwitch: typeof import('./../components/BaseMapSwitch.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    SBaseMap: typeof import('./../components/SBaseMap.vue')['default']
    SMapScene: typeof import('./../components/SMapScene.vue')['default']
    STerrainSwitch: typeof import('./../components/STerrainSwitch.vue')['default']
  }
}
